version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - user-service
      - classroom-service
      - chat-service

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env

  classroom-service:
    build:
      context: .
      dockerfile: apps/classroom-service/Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env

  chat-service:
    build:
      context: .
      dockerfile: apps/chat-service/Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - .env